write_files:
  # Add reverse proxy configuration for ComfyUI with basic authentication
  - path: /etc/caddy/comfystream.caddy
    content: |
      :8189 {
        reverse_proxy http://127.0.0.1:8188
        basic_auth {
          comfyadmin <PASSWORD_PLACEHOLDER>
        }
      }

runcmd:
  # Setup auth proxy for ComfyUI (requires port 8189 to be open)
  - curl -1sLf 'https://dl.cloudsmith.io/public/caddy/testing/gpg.key' | sudo gpg --dearmor -o /usr/share/keyrings/caddy-testing-archive-keyring.gpg
  - curl -1sLf 'https://dl.cloudsmith.io/public/caddy/testing/debian.deb.txt' | sudo tee /etc/apt/sources.list.d/caddy-testing.list
  - sudo apt update
  - sudo apt install -y caddy
  - echo 'import /etc/caddy/comfystream.caddy' | sudo tee -a /etc/caddy/Caddyfile > /dev/null
  - sudo systemctl restart caddy
  # Install, configure, and start Comfystream and ComfyUI
  - docker pull <DOCKER_IMAGE_PLACEHOLDER>
  - mkdir -p ~/models/ComfyUI--models ~/models/ComfyUI--output
  - docker run --restart unless-stopped --stop-timeout 300 --gpus all --name comfystream -v ${HOME}/models/ComfyUI--models:/workspace/ComfyUI/models -v ${HOME}/models/ComfyUI--output:/workspace/ComfyUI/output -p 3000:3000 -p 8188:8188 -p 8889:8889 <DOCKER_IMAGE_PLACEHOLDER> --download-models --build-engines --server
