name: Create release draft

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
    # types: [closed]
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    # if: ${{ github.event.pull_request.merged }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: ui/package-lock.json

      - name: Build project
        env:
          "NEXT_PUBLIC_DEV": "false"
        run: |
          mkdir -p releases/
          cur_dir="$(pwd)"
          cd ui/
          npm ci
          npm run build
          dist_dir="../nodes/web/static/"
          if ! [ test -d "${dist_dir}" ];
          then
            dist_dir="./.next/";
          fi
          cd "$dist_dir"
          zip -DTr9q "${cur_dir}/releases/dist.zip" ./
          cd -

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-artifacts
          path: releases/

      - uses: actions-ecosystem/action-regex-match@v2
        id: match-tag
        with:
          text: ${{ github.event.workflow_run.head_branch }}
          regex: '^v([0-9]+\.\d+\.\d+)$'

      - name: Create release
        if: ${{ steps.match-tag.outputs.match != '' }}
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist.zip
          tag_name: v${{ steps.current_version.outputs.version }}
          target_commitish: ${{ github.event.pull_request.base.ref }}
          make_latest: ${{ github.event.pull_request.base.ref == 'main' }}
          draft: true
          prerelease: false
          generate_release_notes: true
